# Generated by Django 2.2.7 on 2019-11-30 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tution_management_app', '0002_student_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
