# Generated by Django 2.2.7 on 2019-11-30 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tution_management_app', '0004_auto_20191130_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
