# Generated by Django 2.2.7 on 2019-11-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution_management_app', '0006_auto_20191130_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='tution_management_app.Subject'),
        ),
    ]
